### ISSUE TITLE
Do not use deprecated imports and functions

### ISSUE THREAD

**Issue by arendMoerman** [deshima-dev/kidanalysis-delft#2]
When trying to run `Configure.py`, I get an error:
```
Traceback (most recent call last):
  File "/home/arend/Projects/Software/kidanalysis-delft/scripts/aste/Configure.py", line 147, in <module>
    main()
  File "/home/arend/Projects/Software/kidanalysis-delft/scripts/aste/Configure.py", line 101, in main
    import bbsweeplib
  File "/home/arend/Projects/Software/kidanalysis-delft/scripts/libs/bbsweeplib/__init__.py", line 20, in <module>
    from .kids import KIDs
  File "/home/arend/Projects/Software/kidanalysis-delft/scripts/libs/bbsweeplib/kids.py", line 3, in <module>
    from collections import Mapping, OrderedDict
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.11/collections/__init__.py)
```

Then, when trying to run `FitSweep.py`, I get:
```
Traceback (most recent call last):
  File "/home/arend/Projects/Software/kidanalysis-delft/scripts/aste/FitSweep.py", line 384, in <module>
    main()
  File "/home/arend/Projects/Software/kidanalysis-delft/scripts/aste/FitSweep.py", line 131, in main
    failed = Calc(kids, args.nfwhm, args.fitter, args.verbose, args.force,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arend/Projects/Software/kidanalysis-delft/scripts/aste/FitSweep.py", line 167, in Calc
    r = kid.fit(nfwhm, fitter, Q_search=100)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arend/Projects/Software/kidanalysis-delft/scripts/libs/bbsweeplib/cache.py", line 135, in __call__
    result = self.orig_func(self._obj, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arend/Projects/Software/kidanalysis-delft/scripts/libs/bbsweeplib/kids.py", line 448, in fit
    swp = self.get_cache('raw_sweep')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arend/Projects/Software/kidanalysis-delft/scripts/libs/bbsweeplib/cache.py", line 37, in get_cache
    argspec = inspect.getargspec(orig_func)
              ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?
```

My Python version: 3.11.2

When looking up the raised errors, I found that in Python 3.11, `Mapping` is imported from `collections.abc` instead of `collections`, so that is an easy fix.
For the second error, I found that `getargspec` is deprecated. I replaced with `getfullargspec`, adjusted the unpacking of the outputs because it is slightly different from `getargspec`, and everything worked again.

Maybe it is an idea to update the README so that people know that they have to roll back to a specific Python version where this is not breaking/deprecated? I am not sure on what version the program was developed, so I cannot help further with this.

Another idea is to just update these two scripts (see tracebacks) so that the script can also be run on Python 3.11?

If desired, and if idea two is preferred, I can open a pull request containing the specified changes.

**Comment by astropenguin** [comment]
Hi @arendMoerman, thank you for reporting this! I also got the same errors and the fixes you proposed look correct. Because I need to implement the scripts to de:merge asap, please let me fix these by my pull request.
